pipeline:
    dockerhub:
        image: plugins/docker
        repo: thecloudconnectors/drone-nomad
        secrets: [ docker_username, docker_password ]
        tags:
            - "${DRONE_TAG}"
            - latest
        when:
            ref: refs/tags/*
            event: tag
